using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;

// dotnet NetForms.ApiDiff.dll [--types] [--type <FullName>] [--namespace <prefix>] [--ref <dir>]
//
// Lists what the real WinForms (System.Windows.Forms + System.Drawing.Common, from the reference pack)
// has and NetForms has not: missing types, then per type the missing public/protected members, as
// C#-ish signatures. --types: only the missing types. --type: one type's missing members.
var refDir = ArgValue("--ref") ?? typeof(Program).Assembly.GetCustomAttributes<AssemblyMetadataAttribute>()
    .First(a => a.Key == "WindowsDesktopRef").Value!;
if (!Directory.Exists(refDir)) { Console.Error.WriteLine($"No reference pack at {refDir} (restore the project, or pass --ref)."); return 2; }
bool typesOnly = args.Contains("--types");
var onlyType = ArgValue("--type");
var ns = ArgValue("--namespace");

var runtimeDir = RuntimeEnvironment.GetRuntimeDirectory();
var ourDir = AppContext.BaseDirectory;
var real = new MetadataLoadContext(new PathAssemblyResolver(
    Directory.GetFiles(refDir, "*.dll").Concat(Directory.GetFiles(runtimeDir, "*.dll").Where(f => !Directory.GetFiles(refDir, "*.dll").Any(r => Path.GetFileName(r) == Path.GetFileName(f))))));
var ours = new MetadataLoadContext(new PathAssemblyResolver(
    Directory.GetFiles(ourDir, "*.dll").Concat(Directory.GetFiles(runtimeDir, "*.dll")).GroupBy(Path.GetFileName).Select(g => g.First())));

var realTypes = new[] { "System.Windows.Forms.dll", "System.Windows.Forms.Primitives.dll", "System.Drawing.Common.dll" }
    .SelectMany(f => real.LoadFromAssemblyPath(Path.Combine(refDir, f)).GetExportedTypes())
    .Where(t => t.Namespace != null && (t.Namespace.StartsWith("System.Windows.Forms") || t.Namespace.StartsWith("System.Drawing")))
    .Where(t => ns == null || t.Namespace!.StartsWith(ns))
    .ToDictionary(t => Name(t));
var ourTypes = new[] { "NetForms.dll", "NetForms.Drawing.dll" }
    .SelectMany(f => ours.LoadFromAssemblyPath(Path.Combine(ourDir, f)).GetExportedTypes())
    .GroupBy(Name).ToDictionary(g => g.Key, g => g.First());

if (args.Contains("--forwards") || args.Contains("--forwards-winforms"))
{
    // --forwards:          src/NetForms.Drawing.Common/Forwards.cs, the types NetForms.Drawing shares with System.Drawing.Common;
    // --forwards-winforms: src/NetForms.WindowsForms/Forwards.cs, the types NetForms shares with System.Windows.Forms
    //                      (and System.Windows.Forms.Primitives, whose public types WinForms code sees under that name too).
    bool winforms = args.Contains("--forwards-winforms");
    var realFiles = winforms ? new[] { "System.Windows.Forms.dll", "System.Windows.Forms.Primitives.dll" } : new[] { "System.Drawing.Common.dll" };
    var common = realFiles.SelectMany(f => real.LoadFromAssemblyPath(Path.Combine(refDir, f)).GetExportedTypes()).Where(t => !t.IsNested).Select(Name).ToHashSet();
    var shared = ours.LoadFromAssemblyPath(Path.Combine(ourDir, winforms ? "NetForms.dll" : "NetForms.Drawing.dll")).GetExportedTypes()
        .Where(t => !t.IsNested && common.Contains(Name(t))).Select(t => t.IsGenericTypeDefinition ? Name(t).Split('`')[0] + "<>" : Name(t)).OrderBy(n => n, StringComparer.Ordinal);
    Console.WriteLine(winforms
        ? "// Generated by tools/NetForms.ApiDiff --forwards-winforms: the types NetForms shares with System.Windows.Forms (decision 123)."
        : "// Generated by tools/NetForms.ApiDiff --forwards: the types NetForms.Drawing shares with System.Drawing.Common (decision 107).");
    Console.WriteLine();
    foreach (var n in shared) Console.WriteLine($"[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof({n}))]");
    return 0;
}

if (ArgValue("--show") is { } show)
{
    // One real type in full: base, interfaces, attributes of the type, every public/protected member.
    foreach (var name in show.Split(','))
    {
        if (!realTypes.TryGetValue(name, out var t)) { Console.WriteLine($"// {name}: not in the reference pack"); continue; }
        var kind = t.IsEnum ? "enum" : t.IsInterface ? "interface" : t.IsValueType ? "struct" : t.IsSubclassOf(t.BaseType?.Assembly.GetType("System.MulticastDelegate") ?? typeof(object)) && t.BaseType?.FullName == "System.MulticastDelegate" ? "delegate" : (t.IsAbstract && t.IsSealed ? "static class" : t.IsAbstract ? "abstract class" : t.IsSealed ? "sealed class" : "class");
        var bases = new[] { t.BaseType is { } b && b.FullName is not ("System.Object" or "System.ValueType" or "System.Enum" or "System.MulticastDelegate") ? TypeName(b) : null }
            .Concat(t.GetInterfaces().Where(i => t.BaseType == null || !t.BaseType.GetInterfaces().Contains(i)).Select(TypeName)).Where(x => x != null);
        foreach (var a in t.CustomAttributes.Where(a => !a.AttributeType.Name.StartsWith("Nullable") && a.AttributeType.Name != "ObsoleteAttribute" || true))
            Console.WriteLine($"[{a.AttributeType.Name.Replace("Attribute", "")}({string.Join(", ", a.ConstructorArguments.Select(c => c.Value is Type ct ? $"typeof({TypeName(ct)})" : c.Value is string sv ? $"\"{sv}\"" : c.Value?.ToString()))})]");
        Console.WriteLine($"{kind} {name}{(bases.Any() ? " : " + string.Join(", ", bases) : "")}");
        if (t.IsEnum)
        {
            foreach (var f in t.GetFields(BindingFlags.Public | BindingFlags.Static)) Console.WriteLine($"  {f.Name} = {f.GetRawConstantValue()}");
            continue;
        }
        if (kind == "delegate") { Console.WriteLine("  " + Signature(t.GetMethod("Invoke")!)); continue; }
        foreach (var m in Members(t, inherited: false).OrderBy(m => m.MemberType).ThenBy(m => m.Name))
        {
            var attrs = string.Join("", m.CustomAttributes.Where(a => a.AttributeType.Name is "DefaultValueAttribute" or "BrowsableAttribute" or "EditorBrowsableAttribute" or "DesignerSerializationVisibilityAttribute" or "ObsoleteAttribute" or "LocalizableAttribute")
                .Select(a => $"[{a.AttributeType.Name.Replace("Attribute", "")}({string.Join(", ", a.ConstructorArguments.Select(c => c.Value is Type ct ? $"typeof({TypeName(ct)})" : c.Value is string sv ? $"\"{sv}\"" : c.Value?.ToString()))})]"));
            var access = m switch { MethodBase mb => mb.IsFamily ? "protected " : "", PropertyInfo p => (p.GetMethod ?? p.SetMethod)!.IsFamily ? "protected " : "", _ => "" };
            var virt = m switch { MethodInfo mi => mi.IsAbstract ? "abstract " : mi.IsVirtual && !mi.IsFinal ? "virtual " : "", PropertyInfo p => (p.GetMethod ?? p.SetMethod) is { } a && a.IsAbstract ? "abstract " : (p.GetMethod ?? p.SetMethod) is { IsVirtual: true, IsFinal: false } ? "virtual " : "", _ => "" };
            Console.WriteLine($"  {attrs}{access}{virt}{Signature(m)}");
        }
    }
    return 0;
}

var missingTypes = realTypes.Keys.Where(k => !ourTypes.ContainsKey(k)).OrderBy(k => k, StringComparer.Ordinal).ToList();
if (onlyType == null)
{
    Console.WriteLine($"# Missing types: {missingTypes.Count} of {realTypes.Count}");
    foreach (var t in missingTypes) Console.WriteLine(t);
    if (typesOnly) return 0;
}

int total = 0;
foreach (var (name, type) in realTypes.OrderBy(p => p.Key, StringComparer.Ordinal))
{
    if (onlyType != null && name != onlyType) continue;
    if (!ourTypes.TryGetValue(name, out var mine)) continue;
    var have = new HashSet<string>(Members(mine, inherited: true).Select(Signature));
    var missing = Members(type, inherited: false).Select(Signature).Where(s => !have.Contains(s)).Distinct().OrderBy(s => s, StringComparer.Ordinal).ToList();
    if (missing.Count == 0) continue;
    total += missing.Count;
    Console.WriteLine($"\n## {name} ({missing.Count})");
    foreach (var m in missing) Console.WriteLine("  " + m);
}
Console.WriteLine($"\n# Missing members of existing types: {total}");
return 0;

static IEnumerable<MemberInfo> Members(Type t, bool inherited)
{
    var flags = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static | (inherited ? 0 : BindingFlags.DeclaredOnly);
    foreach (var m in t.GetMembers(flags))
    {
        bool visible = m switch
        {
            MethodBase mb => mb.IsPublic || mb.IsFamily || mb.IsFamilyOrAssembly,
            FieldInfo f => f.IsPublic || f.IsFamily || f.IsFamilyOrAssembly,
            PropertyInfo p => (p.GetMethod ?? p.SetMethod) is { } a && (a.IsPublic || a.IsFamily || a.IsFamilyOrAssembly),
            EventInfo e => e.AddMethod is { } a && (a.IsPublic || a.IsFamily || a.IsFamilyOrAssembly),
            Type nested => nested.IsNestedPublic || nested.IsNestedFamily,
            _ => false,
        };
        if (!visible) continue;
        // Accessors are listed with their property/event. Operators are kept: an implicit conversion
        // (TaskDialogFootnote from string) decides whether user code compiles.
        if (m is MethodInfo { IsSpecialName: true } special && !special.Name.StartsWith("op_", StringComparison.Ordinal)) continue;
        if (m is Type) continue; // nested types are compared as types
        // An override is found on our side through inheritance (ours are compared with inherited members).
        yield return m;
    }
}

static string Name(Type t) => (t.FullName ?? t.Name).Replace('+', '.');

static string TypeName(Type t)
{
    if (t.IsByRef) return "ref " + TypeName(t.GetElementType()!);
    if (t.IsArray) return TypeName(t.GetElementType()!) + "[]";
    if (t.IsGenericParameter) return t.Name;
    if (t.IsGenericType)
    {
        var def = Name(t.GetGenericTypeDefinition());
        return def.Substring(0, def.IndexOf('`')) + "<" + string.Join(",", t.GetGenericArguments().Select(TypeName)) + ">";
    }
    return Name(t);
}

static string Signature(MemberInfo m) => m switch
{
    ConstructorInfo c => $".ctor({string.Join(", ", c.GetParameters().Select(p => TypeName(p.ParameterType)))})",
    MethodInfo mi => $"{(mi.IsStatic ? "static " : "")}{TypeName(mi.ReturnType)} {mi.Name}{(mi.IsGenericMethod ? "<" + string.Join(",", mi.GetGenericArguments().Select(a => a.Name)) + ">" : "")}({string.Join(", ", mi.GetParameters().Select(p => TypeName(p.ParameterType)))})",
    PropertyInfo p => $"{TypeName(p.PropertyType)} {p.Name}{(p.GetIndexParameters().Length > 0 ? "[" + string.Join(", ", p.GetIndexParameters().Select(i => TypeName(i.ParameterType))) + "]" : "")} {{{(p.GetMethod != null ? " get;" : "")}{(p.SetMethod is { } s && (s.IsPublic || s.IsFamily) ? " set;" : "")} }}",
    EventInfo e => $"event {TypeName(e.EventHandlerType!)} {e.Name}",
    FieldInfo f => $"{(f.IsLiteral ? "const " : f.IsStatic ? "static " : "")}{TypeName(f.FieldType)} {f.Name}",
    _ => m.Name,
};

string? ArgValue(string name)
{
    int i = Array.IndexOf(args, name);
    return i >= 0 && i + 1 < args.Length ? args[i + 1] : null;
}
