using System.ComponentModel;
using System;
using System.Drawing;
using System.Text;

namespace System.Windows.Forms;

/// <summary>An item that owns a drop-down: a menu item, a drop-down button, the overflow chevron.</summary>
[DefaultProperty("DropDownItems")]
public abstract class ToolStripDropDownItem : ToolStripItem
{
    private ToolStripDropDown? _dropDown;
    private ToolStripDropDownDirection _direction = ToolStripDropDownDirection.Default;

    protected ToolStripDropDownItem() { }

    protected ToolStripDropDownItem(string? text, Image? image, EventHandler? onClick) : base(text, image, onClick) { }

    protected ToolStripDropDownItem(string? text, Image? image, EventHandler? onClick, string? name) : base(text, image, onClick, name) { }

    protected ToolStripDropDownItem(string? text, Image? image, params ToolStripItem[] dropDownItems) : base(text, image, null)
    {
        if (dropDownItems != null) DropDownItems.AddRange(dropDownItems);
    }

    [Category("Action")]
    [Description("Occurs when the DropDown is opening.")]
    public event EventHandler? DropDownOpening;

    [Category("Action")]
    [Description("Occurs when the DropDown has opened.")]
    public event EventHandler? DropDownOpened;

    [Category("Action")]
    [Description("Occurs when the DropDown has closed.")]
    public event EventHandler? DropDownClosed;

    [Category("Action")]
    public event ToolStripItemClickedEventHandler? DropDownItemClicked;

    [Category("Data")]
    [Description("Specifies a ToolStripDropDown to show when the item is clicked.")]
    public ToolStripDropDown DropDown
    {
        get
        {
            if (_dropDown == null)
            {
                _dropDown = CreateDefaultDropDown();
                _dropDown.OwnerItem = this;
                _dropDown.IsAutoGenerated = true;
            }
            return _dropDown;
        }
        set
        {
            if (ReferenceEquals(_dropDown, value)) return;
            if (_dropDown != null) _dropDown.OwnerItem = null;
            _dropDown = value;
            if (value != null)
            {
                value.OwnerItem = this;
                value.IsAutoGenerated = false;
            }
            InvalidateLayout();
        }
    }

    [Category("Data")]
    [Description("Specifies a ToolStripItem to display when the item is clicked.")]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
    public ToolStripItemCollection DropDownItems => DropDown.Items;

    [Browsable(false)]
    public virtual bool HasDropDownItems => _dropDown != null && _dropDown.Items.Count > 0;

    public bool DropDownVisible => _dropDown != null && _dropDown.Visible;

    /// <summary>The drop-down counts as pressed while it is open, so the item stays highlighted.</summary>
    [Localizable(false)]
    [Browsable(false)]
    [EditorBrowsable(EditorBrowsableState.Never)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
    public override bool Pressed => base.Pressed || DropDownVisible;

    [Category("Behavior")]
    [Description("Specifies the direction in which to drop the drop down.")]
    [Browsable(false)]
    public ToolStripDropDownDirection DropDownDirection
    {
        get => _direction;
        set => _direction = value;
    }

    public Point DropDownLocation => GetDropDownScreenLocation();

    protected virtual ToolStripDropDown CreateDefaultDropDown() => new ToolStripDropDownMenu(this, isAutoGenerated: true);

    protected internal virtual void OnDropDownShow(EventArgs e) => DropDownOpening?.Invoke(this, e);

    protected virtual void OnDropDownOpened(EventArgs e) => DropDownOpened?.Invoke(this, e);

    protected virtual void OnDropDownClosed(EventArgs e) => DropDownClosed?.Invoke(this, e);

    protected virtual void OnDropDownItemClicked(ToolStripItemClickedEventArgs e) => DropDownItemClicked?.Invoke(this, e);

    internal void RaiseDropDownOpened() => OnDropDownOpened(EventArgs.Empty);
    internal void RaiseDropDownClosed() => OnDropDownClosed(EventArgs.Empty);
    internal void RaiseDropDownItemClicked(ToolStripItem item) => OnDropDownItemClicked(new ToolStripItemClickedEventArgs(item));

    public void ShowDropDown() => ShowDropDown(false);

    internal void ShowDropDown(bool fromKeyboard)
    {
        if (DropDownVisible || Owner == null) return;
        OnDropDownShow(EventArgs.Empty);
        if (!HasDropDownItems) return;
        DropDown.ShowAtScreen(ResolveDirectionPoint(), ResolveDirection());
        if (fromKeyboard) DropDown.SelectItem(DropDown.GetNextItem(null, ArrowDirection.Down));
        Invalidate();
    }

    public void HideDropDown()
    {
        if (!DropDownVisible) return;
        DropDown.Close(ToolStripDropDownCloseReason.CloseCalled);
        Invalidate();
    }

    private ToolStripDropDownDirection ResolveDirection()
    {
        if (_direction != ToolStripDropDownDirection.Default) return _direction;
        if (IsOnDropDown) return ToolStripDropDownDirection.Right;
        return Owner?.Orientation == Orientation.Vertical ? ToolStripDropDownDirection.Right : ToolStripDropDownDirection.BelowRight;
    }

    private Point ResolveDirectionPoint()
    {
        var owner = Owner;
        if (owner == null) return Point.Empty;
        // A menu-bar item drops from its bottom-left; a submenu opens off its top-right corner.
        var local = IsOnDropDown || owner.Orientation == Orientation.Vertical
            ? new Point(Bounds.Right, Bounds.Top - owner.Padding.Top)
            : new Point(Bounds.Left, Bounds.Bottom);
        return owner.PointToScreen(local);
    }

    private Point GetDropDownScreenLocation() => DropDown.LastScreenLocation ?? ResolveDirectionPoint();

    internal override void HandleClick(EventArgs e)
    {
        // Opening the drop-down is the click for an item that has one. Clicking a top-level
        // menu that is already open closes it; inside a menu the submenu stays put.
        if (HasDropDownItems)
        {
            if (!DropDownVisible) ShowDropDown();
            else if (!IsOnDropDown) HideDropDown();
        }
        base.HandleClick(e);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && _dropDown != null && _dropDown.IsAutoGenerated)
        {
            _dropDown.Dispose();
            _dropDown = null;
        }
        base.Dispose(disposing);
    }

    /// <summary>Only a drop-down the user assigned is written; the one created on demand is not.</summary>
    internal bool ShouldSerializeDropDown() => _dropDown != null && !_dropDown.IsAutoGenerated;

    internal bool ShouldSerializeDropDownDirection() => _direction != ToolStripDropDownDirection.Default;
}

/// <summary>An entry in a menu: text, optional image or check mark, an optional shortcut and submenu.</summary>
public class ToolStripMenuItem : ToolStripDropDownItem
{
    // Layout constants from dotnet/winforms' ToolStripDropDownMenu (logical, 96 DPI).
    private const int TextPaddingLeft = 8;
    private const int TextPaddingRight = 9;
    private const int ArrowPaddingRight = 8;
    private const int ArrowWidth = 10;
    private const int ShortcutGap = 16;

    private bool _checked;
    private CheckState _checkState = CheckState.Unchecked;
    private Keys _shortcutKeys = Keys.None;
    private string? _shortcutKeyDisplayString;
    private bool _showShortcutKeys = true;

    public ToolStripMenuItem() { }
    public ToolStripMenuItem(string? text) : base(text, null, (EventHandler?)null) { }
    public ToolStripMenuItem(Image? image) : base(null, image, (EventHandler?)null) { }
    public ToolStripMenuItem(string? text, Image? image) : base(text, image, (EventHandler?)null) { }
    public ToolStripMenuItem(string? text, Image? image, EventHandler? onClick) : base(text, image, onClick) { }
    public ToolStripMenuItem(string? text, Image? image, EventHandler? onClick, string? name) : base(text, image, onClick, name) { }
    public ToolStripMenuItem(string? text, Image? image, params ToolStripItem[] dropDownItems) : base(text, image, dropDownItems) { }

    public ToolStripMenuItem(string? text, Image? image, EventHandler? onClick, Keys shortcutKeys) : base(text, image, onClick)
    {
        ShortcutKeys = shortcutKeys;
    }

    protected override ToolStripItemOverflow DefaultOverflow => ToolStripItemOverflow.Never;

    [Description("Occurs whenever the Check property is changed.")]
    public event EventHandler? CheckedChanged;

    [Description("Occurs whenever the CheckState property is changed.")]
    public event EventHandler? CheckStateChanged;

    protected override Size DefaultSize => new Size(32, 19);

    protected override Padding DefaultPadding => IsOnDropDown ? new Padding(0, 1, 0, 1) : new Padding(4, 0, 4, 0);

    protected internal override Padding DefaultMargin => Padding.Empty;

    [Category("Behavior")]
    [Description("Indicates whether the item should toggle its selected state when clicked.")]
    [DefaultValue(false)]
    public bool CheckOnClick { get; set; }

    [Category("Appearance")]
    [Description("Indicates whether the component is in the checked state.")]
    [DefaultValue(false)]
    public bool Checked
    {
        get => _checked;
        set => CheckState = value ? CheckState.Checked : CheckState.Unchecked;
    }

    [Category("Appearance")]
    [Description("Indicates the state of the component.")]
    [DefaultValue(CheckState.Unchecked)]
    public CheckState CheckState
    {
        get => _checkState;
        set
        {
            if (_checkState == value) return;
            bool wasChecked = _checked;
            _checkState = value;
            _checked = value != CheckState.Unchecked;
            OnCheckStateChanged(EventArgs.Empty);
            if (wasChecked != _checked) OnCheckedChanged(EventArgs.Empty);
            Invalidate();
        }
    }

    [Description("The shortcut key associated with the menu item.")]
    [DefaultValue(Keys.None)]
    [Localizable(true)]
    public Keys ShortcutKeys
    {
        get => _shortcutKeys;
        set
        {
            if (_shortcutKeys == value) return;
            _shortcutKeys = value;
            InvalidateLayout();
        }
    }

    [Category("Appearance")]
    [Description("The string to be displayed as the shortcut key.")]
    [DefaultValue(null)]
    [Localizable(true)]
    public string? ShortcutKeyDisplayString
    {
        get => _shortcutKeyDisplayString;
        set
        {
            if (_shortcutKeyDisplayString == value) return;
            _shortcutKeyDisplayString = value;
            InvalidateLayout();
        }
    }

    [Description("Indicates whether the shorcut key for the menu item is displayed on the item.")]
    [DefaultValue(true)]
    [Localizable(true)]
    public bool ShowShortcutKeys
    {
        get => _showShortcutKeys;
        set
        {
            if (_showShortcutKeys == value) return;
            _showShortcutKeys = value;
            InvalidateLayout();
        }
    }

    /// <summary>True for the automatic entries an MDI window list adds; we have no MDI yet.</summary>
    [Browsable(false)]
    public bool IsMdiWindowListEntry => false;

    protected virtual void OnCheckedChanged(EventArgs e) => CheckedChanged?.Invoke(this, e);

    protected virtual void OnCheckStateChanged(EventArgs e) => CheckStateChanged?.Invoke(this, e);

    protected override void OnClick(EventArgs e)
    {
        if (CheckOnClick) Checked = !Checked;
        base.OnClick(e);
    }

    // --- layout ---------------------------------------------------------------------------

    internal int ImageMarginWidth => (Owner as ToolStripDropDownMenu)?.ImageMarginWidth ?? 0;

    internal string ShortcutText
    {
        get
        {
            if (!_showShortcutKeys) return string.Empty;
            if (!string.IsNullOrEmpty(_shortcutKeyDisplayString)) return _shortcutKeyDisplayString!;
            return _shortcutKeys == Keys.None ? string.Empty : ShortcutToText(_shortcutKeys);
        }
    }

    public override Size GetPreferredSize(Size constrainingSize)
    {
        if (!AutoSize) return ExplicitSize;
        // On a menu bar an item is sized like any other: content, padding and the 2px border.
        if (!IsOnDropDown) return base.GetPreferredSize(constrainingSize);

        var padding = Padding;

        var textSize = Text.Length > 0 ? TextRenderer.MeasureText(Text, Font, new Size(int.MaxValue, int.MaxValue), TextFormatFlags.SingleLine) : Size.Empty;
        int width = ImageMarginWidth + TextPaddingLeft + textSize.Width + TextPaddingRight;

        var shortcut = ShortcutText;
        if (shortcut.Length > 0)
        {
            width += TextRenderer.MeasureText(shortcut, Font, new Size(int.MaxValue, int.MaxValue), TextFormatFlags.SingleLine).Width + ShortcutGap;
        }
        if (HasDropDownItems) width += ArrowWidth + ArrowPaddingRight;

        // A standard menu row is 22px: a 16px image, the item's 1px padding and the 2px border.
        int height = Math.Max(textSize.Height, Math.Max(ImageSize.Height, 16)) + padding.Vertical + BorderSize * 2;
        return new Size(width, height);
    }

    /// <summary>The check/image square, the text and (on a drop-down) the shortcut and arrow.</summary>
    internal (Rectangle image, Rectangle text, Rectangle shortcut, Rectangle arrow) LayoutMenuItem()
    {
        var bounds = new Rectangle(Point.Empty, Size);
        if (!IsOnDropDown)
        {
            var (text, image) = LayoutContent();
            return (image, text, Rectangle.Empty, Rectangle.Empty);
        }

        int margin = ImageMarginWidth;
        var imageSize = ImageSize.IsEmpty ? new Size(16, 16) : ImageSize;
        var imageRect = new Rectangle(
            Math.Max(0, (margin - imageSize.Width) / 2),
            bounds.Y + (bounds.Height - imageSize.Height) / 2,
            imageSize.Width, imageSize.Height);

        var arrowRect = Rectangle.Empty;
        int right = bounds.Right - TextPaddingRight;
        if (HasDropDownItems)
        {
            arrowRect = new Rectangle(bounds.Right - ArrowPaddingRight - ArrowWidth, bounds.Y, ArrowWidth, bounds.Height);
            right = arrowRect.Left;
        }

        var shortcutRect = Rectangle.Empty;
        var shortcut = ShortcutText;
        if (shortcut.Length > 0)
        {
            var size = TextRenderer.MeasureText(shortcut, Font, new Size(int.MaxValue, int.MaxValue), TextFormatFlags.SingleLine);
            shortcutRect = new Rectangle(right - size.Width, bounds.Y, size.Width, bounds.Height);
            right = shortcutRect.Left - ShortcutGap;
        }

        int textLeft = margin + TextPaddingLeft;
        var textRect = new Rectangle(textLeft, bounds.Y, Math.Max(0, right - textLeft), bounds.Height);
        return (imageRect, textRect, shortcutRect, arrowRect);
    }

    protected override void OnPaint(PaintEventArgs e)
    {
        var renderer = Owner?.Renderer ?? ToolStripManager.Renderer;
        renderer.DrawMenuItemBackground(new ToolStripItemRenderEventArgs(e.Graphics, this));

        var (imageRect, textRect, shortcutRect, arrowRect) = LayoutMenuItem();
        var color = Enabled ? ForeColor : Theme.DisabledText;

        if (IsOnDropDown && Checked)
        {
            renderer.DrawItemCheck(new ToolStripItemImageRenderEventArgs(e.Graphics, this, CheckedImage, imageRect) { IsCheckMark = true });
        }
        else if (Image != null && (DisplayStyle & ToolStripItemDisplayStyle.Image) != 0)
        {
            renderer.DrawItemImage(new ToolStripItemImageRenderEventArgs(e.Graphics, this, Image, imageRect));
        }

        if ((DisplayStyle & ToolStripItemDisplayStyle.Text) != 0 && Text.Length > 0)
        {
            var format = IsOnDropDown
                ? TextFormatFlags.Left | TextFormatFlags.VerticalCenter | TextFormatFlags.SingleLine
                : ToolStripItemTextRenderEventArgs.TranslateAlignment(TextAlign) | TextFormatFlags.SingleLine;
            renderer.DrawItemText(new ToolStripItemTextRenderEventArgs(e.Graphics, this, Text, textRect, color, Font, format));
        }

        if (!shortcutRect.IsEmpty)
        {
            renderer.DrawItemText(new ToolStripItemTextRenderEventArgs(e.Graphics, this, ShortcutText, shortcutRect,
                Enabled ? Theme.DisabledText : Theme.DisabledText, Font,
                TextFormatFlags.Left | TextFormatFlags.VerticalCenter | TextFormatFlags.SingleLine));
        }

        if (!arrowRect.IsEmpty)
        {
            renderer.DrawArrow(new ToolStripArrowRenderEventArgs(e.Graphics, this, arrowRect, color, ArrowDirection.Right));
        }

        base.OnPaint(e);
    }

    /// <summary>Null means "draw the built-in tick"; an item with its own image keeps showing it when checked.</summary>
    private Image? CheckedImage => (DisplayStyle & ToolStripItemDisplayStyle.Image) != 0 ? Image : null;

    // --- shortcut text -----------------------------------------------------------------------

    /// <summary>Formats a shortcut the way the menu shows it: "Ctrl+Shift+S".</summary>
    internal static string ShortcutToText(Keys shortcut)
    {
        var sb = new StringBuilder();
        if ((shortcut & Keys.Control) != 0) sb.Append("Ctrl+");
        if ((shortcut & Keys.Shift) != 0) sb.Append("Shift+");
        if ((shortcut & Keys.Alt) != 0) sb.Append("Alt+");
        sb.Append(KeyName(shortcut & Keys.KeyCode));
        return sb.ToString();
    }

    private static string KeyName(Keys key) => key switch
    {
        >= Keys.D0 and <= Keys.D9 => ((char)('0' + (key - Keys.D0))).ToString(),
        >= Keys.NumPad0 and <= Keys.NumPad9 => "NumPad" + (key - Keys.NumPad0),
        Keys.Oemplus => "+",
        Keys.OemMinus => "-",
        Keys.Oemcomma => ",",
        Keys.OemPeriod => ".",
        Keys.OemQuestion => "/",
        Keys.Oemtilde => "`",
        Keys.OemOpenBrackets => "[",
        Keys.OemCloseBrackets => "]",
        Keys.OemPipe => "\\",
        Keys.OemSemicolon => ";",
        Keys.OemQuotes => "'",
        Keys.Delete => "Del",
        Keys.Insert => "Ins",
        Keys.PageUp => "PgUp",
        Keys.PageDown => "PgDn",
        Keys.Escape => "Esc",
        Keys.Return => "Enter",
        _ => key.ToString(),
    };

    // Members WinForms hides or re-defaults on this control; TypeDescriptor reads them
    // off the derived type, so they have to be re-declared here to be advertised differently.

    [Category("Layout")]
    [DefaultValue(ToolStripItemOverflow.Never)]
    [Localizable(false)]
    [Browsable(true)]
    [EditorBrowsable(EditorBrowsableState.Always)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Visible)]
    public new ToolStripItemOverflow Overflow { get => base.Overflow; set => base.Overflow = value; }
}

/// <summary>A tool-bar button whose whole surface opens a drop-down.</summary>
public class ToolStripDropDownButton : ToolStripDropDownItem
{
    private const int ArrowWidth = 9;

    public ToolStripDropDownButton() { }
    public ToolStripDropDownButton(string? text) : base(text, null, (EventHandler?)null) { }
    public ToolStripDropDownButton(Image? image) : base(null, image, (EventHandler?)null) { }
    public ToolStripDropDownButton(string? text, Image? image) : base(text, image, (EventHandler?)null) { }
    public ToolStripDropDownButton(string? text, Image? image, EventHandler? onClick) : base(text, image, onClick) { }
    public ToolStripDropDownButton(string? text, Image? image, EventHandler? onClick, string? name) : base(text, image, onClick, name) { }
    public ToolStripDropDownButton(string? text, Image? image, params ToolStripItem[] dropDownItems) : base(text, image, dropDownItems) { }

    protected override bool DefaultAutoToolTip => true;

    [Category("Appearance")]
    [Description("Specifies whether or not an arrow should be shown on the drop down button.")]
    [DefaultValue(true)]
    public bool ShowDropDownArrow { get; set; } = true;

    protected override Padding DefaultPadding => new Padding(1);

    public override Size GetPreferredSize(Size constrainingSize)
    {
        var size = base.GetPreferredSize(constrainingSize);
        if (ShowDropDownArrow) size.Width += ArrowWidth;
        return size;
    }

    protected override void OnPaint(PaintEventArgs e)
    {
        var renderer = Owner?.Renderer ?? ToolStripManager.Renderer;
        renderer.DrawDropDownButtonBackground(new ToolStripItemRenderEventArgs(e.Graphics, this));
        PaintContent(e, renderer, ShowDropDownArrow ? ArrowWidth : 0);
        if (ShowDropDownArrow)
        {
            var arrow = new Rectangle(Width - ArrowWidth - 1, 0, ArrowWidth, Height);
            renderer.DrawArrow(new ToolStripArrowRenderEventArgs(e.Graphics, this, arrow, Enabled ? ForeColor : Theme.DisabledText, ArrowDirection.Down));
        }
        base.OnPaint(e);
    }

    private protected void PaintContent(PaintEventArgs e, ToolStripRenderer renderer, int reservedRight)
    {
        // Lay the content out in the area left of the arrow.
        var content = ContentRectangle;
        var (text, image) = LayoutContent(new Rectangle(content.X, content.Y, Math.Max(0, content.Width - reservedRight), content.Height));

        if (image.Width > 0 && Image != null)
        {
            renderer.DrawItemImage(new ToolStripItemImageRenderEventArgs(e.Graphics, this, Image, image));
        }
        if (text.Width > 0 && Text.Length > 0)
        {
            renderer.DrawItemText(new ToolStripItemTextRenderEventArgs(e.Graphics, this, Text, text,
                Enabled ? ForeColor : Theme.DisabledText, Font, ToolStripItemTextRenderEventArgs.TranslateAlignment(TextAlign) | TextFormatFlags.SingleLine));
        }
    }

    // Members WinForms hides or re-defaults on this control; TypeDescriptor reads them
    // off the derived type, so they have to be re-declared here to be advertised differently.

    [Category("Behavior")]
    [DefaultValue(true)]
    [Localizable(false)]
    [Browsable(true)]
    [EditorBrowsable(EditorBrowsableState.Always)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Visible)]
    public new bool AutoToolTip { get => base.AutoToolTip; set => base.AutoToolTip = value; }
}

/// <summary>A button with a separate arrow half: clicking the button fires ButtonClick, the arrow opens the menu.</summary>
[DefaultEvent("ButtonClick")]
public class ToolStripSplitButton : ToolStripDropDownItem
{
    private int _dropDownButtonWidth = 11;
    private ToolStripItem? _defaultItem;

    public ToolStripSplitButton() { }
    public ToolStripSplitButton(string? text) : base(text, null, (EventHandler?)null) { }
    public ToolStripSplitButton(Image? image) : base(null, image, (EventHandler?)null) { }
    public ToolStripSplitButton(string? text, Image? image) : base(text, image, (EventHandler?)null) { }
    public ToolStripSplitButton(string? text, Image? image, EventHandler? onClick) : base(text, image, onClick) { }
    public ToolStripSplitButton(string? text, Image? image, EventHandler? onClick, string? name) : base(text, image, onClick, name) { }
    public ToolStripSplitButton(string? text, Image? image, params ToolStripItem[] dropDownItems) : base(text, image, dropDownItems) { }

    protected override bool DefaultAutoToolTip => true;

    [Category("Action")]
    [Description("Occurs when the button portion of the split button has been clicked.")]
    public event EventHandler? ButtonClick;

    [Category("Action")]
    [Description("Occurs when the DefaultItem property has changed.")]
    public event EventHandler? DefaultItemChanged;

    [Category("Layout")]
    [Description("Specifies how much space to give to the DropDownButton portion of the ToolStripSplitButton.")]
    public int DropDownButtonWidth
    {
        get => _dropDownButtonWidth;
        set
        {
            if (value < 0) throw new ArgumentOutOfRangeException(nameof(value));
            if (_dropDownButtonWidth == value) return;
            _dropDownButtonWidth = value;
            InvalidateLayout();
        }
    }

    internal bool ShouldSerializeDropDownButtonWidth() => _dropDownButtonWidth != 11;

    public void ResetDropDownButtonWidth() => DropDownButtonWidth = 11;

    [Browsable(false)]
    public Rectangle ButtonBounds => new Rectangle(0, 0, Math.Max(0, Width - _dropDownButtonWidth), Height);

    [Browsable(false)]
    public Rectangle DropDownButtonBounds => new Rectangle(Math.Max(0, Width - _dropDownButtonWidth), 0, _dropDownButtonWidth, Height);

    [Browsable(false)]
    public Rectangle SplitterBounds => new Rectangle(Math.Max(0, Width - _dropDownButtonWidth), 0, 1, Height);

    [Browsable(false)]
    public bool ButtonPressed { get; private set; }

    [Browsable(false)]
    public bool ButtonSelected => Selected && !DropDownButtonSelected;

    [Browsable(false)]
    public bool DropDownButtonPressed => DropDownVisible;

    [Browsable(false)]
    public bool DropDownButtonSelected { get; private set; }

    [DefaultValue(null)]
    [Browsable(false)]
    public ToolStripItem? DefaultItem
    {
        get => _defaultItem;
        set
        {
            if (ReferenceEquals(_defaultItem, value)) return;
            _defaultItem = value;
            OnDefaultItemChanged(EventArgs.Empty);
        }
    }

    protected virtual void OnDefaultItemChanged(EventArgs e) => DefaultItemChanged?.Invoke(this, e);

    protected virtual void OnButtonClick(EventArgs e) => ButtonClick?.Invoke(this, e);

    public void PerformButtonClick()
    {
        if (!Enabled) return;
        OnButtonClick(EventArgs.Empty);
        _defaultItem?.PerformClick();
    }

    public override Size GetPreferredSize(Size constrainingSize)
    {
        var size = base.GetPreferredSize(constrainingSize);
        size.Width += _dropDownButtonWidth;
        return size;
    }

    internal override void HandleMouseDown(MouseEventArgs e)
    {
        ButtonPressed = ButtonBounds.Contains(e.Location);
        DropDownButtonSelected = !ButtonPressed;
        base.HandleMouseDown(e);
    }

    internal override void HandleMouseMove(MouseEventArgs e)
    {
        bool onArrow = DropDownButtonBounds.Contains(e.Location);
        if (onArrow != DropDownButtonSelected)
        {
            DropDownButtonSelected = onArrow;
            Invalidate();
        }
        base.HandleMouseMove(e);
    }

    internal override void HandleClick(EventArgs e)
    {
        if (ButtonPressed)
        {
            ButtonPressed = false;
            OnClick(e);
            OnButtonClick(EventArgs.Empty);
            _defaultItem?.PerformClick();
            Owner?.HandleItemClick(this);
            return;
        }
        if (DropDownVisible) HideDropDown();
        else ShowDropDown();
    }

    protected override void OnPaint(PaintEventArgs e)
    {
        var renderer = Owner?.Renderer ?? ToolStripManager.Renderer;
        renderer.DrawSplitButton(new ToolStripItemRenderEventArgs(e.Graphics, this));

        var (text, image) = LayoutContent(Rectangle.Intersect(ContentRectangle, ButtonBounds));
        if (Image != null && image.Width > 0)
        {
            renderer.DrawItemImage(new ToolStripItemImageRenderEventArgs(e.Graphics, this, Image, image));
        }
        if (Text.Length > 0 && text.Width > 0)
        {
            renderer.DrawItemText(new ToolStripItemTextRenderEventArgs(e.Graphics, this, Text, text,
                Enabled ? ForeColor : Theme.DisabledText, Font, ToolStripItemTextRenderEventArgs.TranslateAlignment(TextAlign) | TextFormatFlags.SingleLine));
        }
        renderer.DrawArrow(new ToolStripArrowRenderEventArgs(e.Graphics, this, DropDownButtonBounds,
            Enabled ? ForeColor : Theme.DisabledText, ArrowDirection.Down));
        base.OnPaint(e);
    }

    // Members WinForms hides or re-defaults on this control; TypeDescriptor reads them
    // off the derived type, so they have to be re-declared here to be advertised differently.

    [Category("Behavior")]
    [DefaultValue(true)]
    [Localizable(false)]
    [Browsable(true)]
    [EditorBrowsable(EditorBrowsableState.Always)]
    [DesignerSerializationVisibility(DesignerSerializationVisibility.Visible)]
    public new bool AutoToolTip { get => base.AutoToolTip; set => base.AutoToolTip = value; }
}
